---
params:
  country: ""
title: '<span style="color:red;">DRAFT</span> Mapping Behavioral Risk Data: `r params$country`'
date: "`r Sys.Date()`"
output:
  html_document:
    keep_md: false
    theme: readable
    toc: true
    toc_float: true
    highlight: pygments
---

```{r setup, include=FALSE}

purrr::walk(list.files(here::here("R/"), full.names = TRUE),
            source, echo = FALSE, verbose = FALSE)
library(leaflet.minicharts)

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, error = FALSE, out.extra = '')
country <- "Bangladesh"#params$country

# Read in data
dat <- read_csv(h(paste0("data/raw-behav-", country, ".csv")), col_types = raw_specs) 

# Get Site names
site_names <- read_csv(h(paste0("data/site-name-formatted-", country, ".csv")), col_types = cols())

# Cleaning
fdat <- dat %>% 
  left_join(site_names, by = c("country" = "country", "concurrent_sampling_site" = "old")) %>%
  group_by(concurrent_sampling_site) %>% 
  mutate(site_latitude = mean(site_latitude), 
         site_longitude = mean(site_longitude),
         site_name = gsub(" ", "-", tolower(concurrent_sampling_site))) %>%  # take average to handle some inconsistencies
  ungroup() %>%
  rename(hovertext = new)

```


```{r get-adm, include=FALSE}
# Get administrative borders of countries of interest
country_wrld <-  str_replace_all(country,
                                 c("\\-.*" = "", 
                                   "^DR" = "Democratic Republic of the",
                                   "PDR" = "People's Democratic Republic",
                                   "Myanmar" = "Burma",
                                   "Vietnam" = "Viet Nam",
                                   "Tanzania" = "United Republic of Tanzania",
                                   "Ivory Coast" = "Cote d'Ivoire",
                                   "Republic of Congo" = "Congo",
                                   "South Sudan"= "Sudan"
                                 ))

data(wrld_simpl)
admin <- wrld_simpl[wrld_simpl@data$NAME %in% country_wrld, ]

```


```{r map}
colors <- c( viridis::viridis_pal()(3)[1], viridis::viridis_pal()(3)[2])

quest <- fdat %>%
  mutate(hovertext = gsub("Concurrent ", "", hovertext)) %>% 
  group_by(country, site_latitude, site_longitude, full_site_name, site_name, concurrent_sampling_site, n, hovertext, handle_animals_life) %>%
  count() %>% 
  ungroup() %>% 
  pivot_wider(names_from = handle_animals_life, values_from = nn, values_fill = list(nn = 0))

 title <- tags$div(
   HTML('<a alt="c" width="300" height="100"> </a>')
 ) 
 
 
 tag.map.title <- tags$style(HTML("
  .leaflet-control.map-title { 
    transform: translate(-50%,20%);
    position: fixed !important;
    left: 50%;
    text-align: center;
    padding-left: 10px; 
    padding-right: 10px; 
    background: rgba(255,255,255,0.75);
    font-weight: bold;
    font-size: 28px;
  }
"))

title <- tags$div(
  tag.map.title, HTML("Handled Animals (lifetime)")
)  
# Map  
leaflet(quest) %>%
  addProviderTiles("CartoDB.Positron") %>% 
  addMinicharts(
    quest$site_longitude, quest$site_latitude,
    type = "pie",
    chartdata = quest[, c("yes", "no")], 
    colorPalette  = colors, legendPosition = "bottomleft",
    width = 40 * sqrt(quest$n) / sqrt(max(quest$n)), transitionTime = 0) %>%
   addControl(title, position = "bottomleft")

```

```{r map2}
library("rnaturalearth")
library("rnaturalearthdata")
library(scatterpie)
library(ggrepel)

countrymap <- ne_countries(scale = "medium", returnclass = "sf", country = country)

max_n <- max(quest$n)

ggplot(countrymap) + 
  geom_sf() +
  geom_scatterpie(data = quest,
                  aes(x=site_longitude, y=site_latitude, r =  0.2*sqrt(n)/sqrt(max_n)),
                  cols=c("yes", "no")) +
  scale_fill_manual(breaks=c("yes","no"), values = c("yes" = viridis::viridis_pal()(3)[1], "no" = viridis::viridis_pal()(3)[2])) +
  geom_label_repel(
    data = quest, aes(x=site_longitude, y=site_latitude, label = hovertext),
    point.padding = 0.5,
   force = 10)+
  theme_map() +
  labs(fill = "Handled Animals (lifetime)")


```

