---
params:
  country: ""
  illness_outcomes: ""
  taxa_outcomes: ""
title: '<span style="color:red;">DRAFT</span> Outcome Prevalence: `r params$country`'
date: "`r Sys.Date()`"
output:
  html_document:
    keep_md: false
---
```{r setup, include=FALSE}
purrr::walk(list.files(here::here("R/"), full.names = TRUE),
            source, echo = FALSE, verbose = FALSE)

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

country <- params$country
illness_outcomes <- params$illness_outcomes
taxa_outcomes <- params$taxa_outcomes
taxa_contact_outcomes <- if(!is.null(taxa_outcomes)){ paste0(taxa_outcomes, "_contact") }
outcomes <- c(illness_outcomes, taxa_contact_outcomes)

# Read in data
dat <- read_csv( h(paste0("data/logic-behav-", country, ".csv")))
```

#### Taxa 
```{r prev-taxa-table}
for(endpt in taxa_outcomes){
  dat <- dat %>%
    mutate(!!paste0(endpt, "_contact") := ifelse(!!sym(paste0("no_", endpt, "_contact")), FALSE, TRUE)) 
}

n <- nrow(dat)
suppressWarnings(
  dat %>%
    select(one_of(taxa_contact_outcomes)) %>%
    gather(key = "outcome") %>%
    group_by(outcome) %>%
    summarize(`prevalence (%)`= round(sum((value)/n * 100), 1)) %>%
    arrange(-`prevalence (%)`) %>%
    kable() %>%
    kable_styling(bootstrap_options = c("striped"), full_width = F,  position = "left")
)
```

#### Illness 
```{r prev-illness-table}
n <- nrow(dat)
suppressWarnings(
  dat %>%
    select(one_of(illness_outcomes)) %>%
    gather(key = "outcome") %>%
    group_by(outcome) %>%
    summarize(`prevalence (%)` = round(sum((value)/n * 100), 1)) %>%
    arrange(-`prevalence (%)`) %>%
    kable() %>%
    kable_styling(bootstrap_options = c("striped"), full_width = F,  position = "left")
)
```

