---
params:
  country: "Indonesia"
title: '<span style="color:red;">DRAFT</span> Behavioral Report: `r params$country`'
date: "`r Sys.Date()`"
output:
  html_document:
    keep_md: false
---
```{r setup, include=FALSE}
purrr::walk(list.files(here::here("R/"), full.names = TRUE),
            source, echo = FALSE, verbose = FALSE)

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
country <- params$country

# Read in data
dat <- read_csv(h(paste0("data/raw-behav-", country, ".csv"))) 

# Get Site names
site_names <- read_csv(h(paste0("data/site-name-formatted-", country, ".csv")))
```

<small>_Click on the_ ▶ _︎arrows to expand sections._</small>


<details>
<summary>Site Characteristics</summary>
```{r site-general-table}
# Seasons
season_sites <- get_sum_table(dat, 
                              pretty_names = site_names, 
                              group_var = "season", 
                              factor_levels = c("Dry",
                                                "Wet"),
                              factor_lab = c("dry",
                                             "wet"),
                              table_lab="Sampling Season")


# human_density_impact
sites_human_density_impact <- get_sum_table(dat, 
                                            pretty_names = site_names, 
                                            group_var = "human_density_impact", 
                                            factor_levels = c("urban",
                                                              "peri-urban",
                                                              "rural",       
                                                              "low disturbance"), 
                                            table_lab="Human Density at Sampling Sites")


# disease_transmission_interfaces
sites_disease_transmission_interfaces <- get_sum_table(dat, 
                                                       pretty_names = site_names, 
                                                       group_var = "disease_transmission_interfaces", 
                                                       factor_levels = c("animal production",
                                                                         "crop production", 
                                                                         "dwellings and temporary settlements",
                                                                         "extractive industry",
                                                                         "market and value chain", 
                                                                         "natural areas", 
                                                                         "wildlife restaurant", 
                                                                         "human hospital",
                                                                         "zoos and sanctuaries",
                                                                         "outbreak investigation"), 
                                                       table_lab="Disease Transmission Interface at Sampling Sites",
                                                       asterisk = TRUE)


# veterinarian_care
sites_veterinarian_care <- get_sum_table(dat, 
                                         pretty_names = site_names, 
                                         group_var = "veterinarian_care", 
                                         factor_levels = c("yes",
                                                           "no",
                                                           "N/A"), 
                                         table_lab="Veterinarian Care at Sampling Sites")


# sampling_area_size
sites_sampling_area_size <- get_sum_table(dat, 
                                          pretty_names = site_names, 
                                          group_var = "sampling_area_size", 
                                          factor_levels = c("small <650 square meters",
                                                            "medium 650-3500 square meters",
                                                            "large 3500-7000 square meters",       
                                                            "extra large >7000 square meters",
                                                            "N/A"),
                                          table_lab="Size of Sampling Sites")

# Together
out <- bind_rows(season_sites, sites_human_density_impact, sites_disease_transmission_interfaces, sites_veterinarian_care, sites_sampling_area_size)

format_sum_table(out, footer = TRUE) 

```
</details>

<details>
<summary>Humans and Animals Present at Sampling</summary>
```{r present-animals-table}

# humans_present
humans_present_sites <- get_sum_table(dat, 
                                      pretty_names = site_names, 
                                      group_var = "humans_present", 
                                      factor_levels = c("none present",
                                                        "1-10",
                                                        "11-100",       
                                                        "101-1000",        
                                                        ">1000"), 
                                      table_lab="Humans Present at Sampling Sites")


# rodents_present
rodents_present_sites <- get_sum_table(dat, 
                                       pretty_names = site_names, 
                                       group_var = "rodents_present", 
                                       factor_levels = c("none present",
                                                         "1-10",
                                                         "11-100",       
                                                         "101-1000",        
                                                         ">1000"), 
                                       table_lab="Rodents Present at Sampling Sites")

# bats_present
bats_present_sites <- get_sum_table(dat, 
                                    pretty_names = site_names, 
                                    group_var = "bats_present", 
                                    factor_levels = c("none present",
                                                      "1-10",
                                                      "11-100",       
                                                      "101-1000",        
                                                      ">1000"), 
                                    table_lab="Bats Present at Sampling Sites")

# nhp_present
nhp_present_sites <- get_sum_table(dat, 
                                   pretty_names = site_names, 
                                   group_var = "nhp_present", 
                                   factor_levels = c("none present",
                                                     "1-10",
                                                     "11-100",       
                                                     "101-1000",        
                                                     ">1000"), 
                                   table_lab="Primates Present at Sampling Sites")

# birds_present
birds_present_sites <- get_sum_table(dat, 
                                     pretty_names = site_names, 
                                     group_var = "birds_present", 
                                     factor_levels = c("none present",
                                                       "1-10",
                                                       "11-100",       
                                                       "101-1000",        
                                                       ">1000"), 
                                     table_lab="Birds Present at Sampling Sites")

# carnivores_present
carnivores_present_sites <- get_sum_table(dat, 
                                          pretty_names = site_names, 
                                          group_var = "carnivores_present", 
                                          factor_levels = c("none present",
                                                            "1-10",
                                                            "11-100",       
                                                            "101-1000",        
                                                            ">1000"), 
                                          table_lab="Carnivores Present at Sampling Sites")

# ungulates_present
ungulates_present_sites <- get_sum_table(dat, 
                                         pretty_names = site_names, 
                                         group_var = "ungulates_present", 
                                         factor_levels = c("none present",
                                                           "1-10",
                                                           "11-100",       
                                                           "101-1000",        
                                                           ">1000"), 
                                         table_lab="Ungulates Present at Sampling Sites")

# pangolins_present
pangolins_present_sites <- get_sum_table(dat, 
                                         pretty_names = site_names, 
                                         group_var = "pangolins_present", 
                                         factor_levels = c("none present",
                                                           "1-10",
                                                           "11-100",       
                                                           "101-1000",        
                                                           ">1000"), 
                                         table_lab="Pangolins Present at Sampling Sites")


# poultry_present
poultry_present_sites <- get_sum_table(dat, 
                                       pretty_names = site_names, 
                                       group_var = "poultry_present", 
                                       factor_levels = c("none present",
                                                         "1-10",
                                                         "11-100",       
                                                         "101-1000",        
                                                         ">1000"), 
                                       table_lab="Poultry Present at Sampling Sites")


# goats_present
goats_present_sites <- get_sum_table(dat, 
                                     pretty_names = site_names, 
                                     group_var = "goats_present", 
                                     factor_levels = c("none present",
                                                       "1-10",
                                                       "11-100",       
                                                       "101-1000",        
                                                       ">1000"), 
                                     table_lab="Goats Present at Sampling Sites")

# camels_present
camels_present_sites <- get_sum_table(dat, 
                                      pretty_names = site_names, 
                                      group_var = "camels_present", 
                                      factor_levels = c("none present",
                                                        "1-10",
                                                        "11-100",       
                                                        "101-1000",        
                                                        ">1000"), 
                                      table_lab="Camels Present at Sampling Sites")


# swine_present
swine_present_sites <- get_sum_table(dat, 
                                     pretty_names = site_names, 
                                     group_var = "swine_present", 
                                     factor_levels = c("none present",
                                                       "1-10",
                                                       "11-100",       
                                                       "101-1000",        
                                                       ">1000"), 
                                     table_lab="Swine Present at Sampling Sites")


# cattle_present
cattle_present_sites <- get_sum_table(dat, 
                                      pretty_names = site_names, 
                                      group_var = "cattle_present", 
                                      factor_levels = c("none present",
                                                        "1-10",
                                                        "11-100",       
                                                        "101-1000",        
                                                        ">1000"), 
                                      table_lab="Cattle Present at Sampling Sites")


# dogs_present
dogs_present_sites <- get_sum_table(dat, 
                                    pretty_names = site_names, 
                                    group_var = "dogs_present", 
                                    factor_levels = c("none present",
                                                      "1-10",
                                                      "11-100",       
                                                      "101-1000",        
                                                      ">1000"), 
                                    table_lab="Dogs Present at Sampling Sites")


# cats_present
cats_present_sites <- get_sum_table(dat, 
                                    pretty_names = site_names, 
                                    group_var = "cats_present", 
                                    factor_levels = c("none present",
                                                      "1-10",
                                                      "11-100",       
                                                      "101-1000",        
                                                      ">1000"), 
                                    table_lab="Cats Present at Sampling Sites")


# Together
out <- bind_rows(humans_present_sites, rodents_present_sites, bats_present_sites,nhp_present_sites, birds_present_sites, carnivores_present_sites, ungulates_present_sites, pangolins_present_sites, poultry_present_sites, goats_present_sites, camels_present_sites, swine_present_sites, cattle_present_sites, dogs_present_sites, cats_present_sites)

format_sum_table(out, footer = FALSE) 

```
</details>

<details>
<summary>Site Water and Vector Characteristics</summary>
```{r site_water_vector-table}

# drinking_water_shared
sites_drinking_water_shared <- get_sum_table(dat, 
                                             pretty_names = site_names, 
                                             group_var = "drinking_water_shared", 
                                             factor_levels = c("yes",
                                                               "no",
                                                               "unknown"), 
                                             table_lab="Drinking Water Shared Between Animals and Humans at Sampling Sites")


# bathing_water_shared
sites_bathing_water_shared <- get_sum_table(dat, 
                                            pretty_names = site_names, 
                                            group_var = "bathing_water_shared", 
                                            factor_levels = c("yes",
                                                              "no",
                                                              "unknown"), 
                                            table_lab="Bathing Water Shared Between Animals and Humans at Sampling Sites")

# toilets_available
sites_toilets_available <- get_sum_table(dat, 
                                         pretty_names = site_names, 
                                         group_var = "toilets_available", 
                                         factor_levels = c("well maintained",
                                                           "not maintained",
                                                           "used",
                                                           "not used",
                                                           "none observed"), 
                                         table_lab="Toilets Available at Sampling Sites",
                                         asterisk = TRUE)

# drinking_water_source
sites_drinking_water_source <- get_sum_table(dat, 
                                             pretty_names = site_names, 
                                             group_var = "drinking_water_source_site", 
                                             factor_levels = c("fully unprotected: pond, uncovered well",
                                                               "rainwater harvesting, water trucking",
                                                               "fully protected: water network with taps, covered well",
                                                               "none observed"), 
                                             table_lab="Drinking Water Source at Sampling Sites",
                                             asterisk = TRUE)

#average_trip_to_water
sites_average_trip_to_water <- get_sum_table(dat, 
                                             pretty_names = site_names, 
                                             group_var = "average_trip_to_water", 
                                             factor_levels = c("<5 minutes walking",
                                                               "5-30 minutes walking",
                                                               ">30 minutes walking",
                                                               "N/A"),
                                             table_lab="Average Trip to Water Sampling Sites")


# insect_vectors
sites_insect_vectors <- get_sum_table(dat, 
                                      pretty_names = site_names, 
                                      group_var = "insect_vectors", 
                                      factor_levels = c("mosquito",
                                                        "sand",
                                                        "tsetse",       
                                                        "tick",        
                                                        "other",
                                                        "none observed"), 
                                      factor_lab = c("mosquito",
                                                     "sand fly",
                                                     "tsetse fly",
                                                     "tick",
                                                     "other",
                                                     "none observed"),
                                      table_lab="Insect Vectors at Sampling Sites",
                                      asterisk = TRUE)

# vector_control_measures
sites_vector_control <- get_sum_table(dat, 
                                      pretty_names = site_names, 
                                      group_var = "vector_control_measures", 
                                      factor_levels = c("yes",
                                                        "no"), 
                                      table_lab="Vector Control Measures Observed at Sampling Sites")


# community_engagement
community_engagement_sites <- get_sum_table(dat, 
                                            pretty_names = site_names, 
                                            group_var = "community_engagement", 
                                            factor_levels = c("yes",
                                                              "no",
                                                              "N/A"),
                                            factor_lab = c("yes",
                                                           "no",
                                                           "unknown"),
                                            table_lab="Community Engagement at Sampling Sites")


# Together
out <- bind_rows(sites_drinking_water_shared, sites_bathing_water_shared, sites_toilets_available, sites_drinking_water_source, sites_average_trip_to_water, sites_insect_vectors, sites_vector_control, community_engagement_sites)

format_sum_table(out, footer = TRUE) 

```
</details>

<details>
<summary>Respondent Characteristics</summary>
```{r respondent-table}
# Gender
gender_table <- get_sum_table(dat, 
                              pretty_names = site_names, 
                              group_var = "gender", 
                              factor_levels = c("male", 
                                                "female", 
                                                "other"), 
                              table_lab = "Gender")

# Education
edu_table_participant <- get_sum_table(dat, 
                                       pretty_names = site_names, 
                                       group_var = "highest_education", 
                                       factor_levels = c("none", 
                                                         "primary school",
                                                         "secondary school",
                                                         "college/university/professional",
                                                         "missing"), 
                                       table_lab="Education (highest level completed)\nRespondent")

edu_table_mother <- get_sum_table(dat, 
                                  pretty_names = site_names, 
                                  group_var = "highest_education_mother", 
                                  factor_levels = c("none", 
                                                    "primary school", 
                                                    "secondary school", 
                                                    "college/university/professional", 
                                                    "missing"), 
                                  table_lab="Education (highest level completed)\nMother")

edu_table <- bind_rows(edu_table_participant, edu_table_mother)

# Time at location
time_table <- get_sum_table(dat, 
                            pretty_names = site_names, 
                            group_var = "length_lived", 
                            factor_levels = c("<1 month", 
                                              "1 month - 1 year", 
                                              ">1 - 5 years", 
                                              ">5 - 10 years", 
                                              ">10 years"), 
                            table_lab="Length of Time Living at Location")

# Job
job_table <- get_sum_table(dat, 
                           pretty_names = site_names, 
                           group_var = "job_position", 
                           factor_levels = c("manager/owner/foreman", 
                                             "worker", 
                                             "live and work at home independently", 
                                             "professional", 
                                             "other", 
                                             "missing"), 
                           table_lab="Job Posiition")

# Livelihood
liv_table_all <- get_sum_table(dat, 
                               pretty_names = site_names, 
                               group_var = "livelihoods",
                               factor_levels = c("crop production", 
                                                 "wild/exotic animal trade/market business", 
                                                 "rancher/farmer animal production business", 
                                                 "meat processing, slaughterhouse, abattoir",
                                                 "hunter/trapper/fisher", 
                                                 "migrant laborer", 
                                                 "nurse, doctor, traditional healer, community health worker", 
                                                 "construction", 
                                                 "extraction of minerals, gas, oil, timber",
                                                 "forager/gatherer/non-timber forest product collector",
                                                 "grocery (vegetables)", "wildlife restaurant business" ,
                                                 "zoo/sanctuary animal health care", 
                                                 "other",
                                                 "missing"),
                               table_lab="Livelihood Activities (past year)\nAll",
                               asterisk = TRUE)


liv_table_pri <- get_sum_table(dat, 
                               pretty_names = site_names, 
                               group_var = "primary_livelihood",
                               factor_levels = c("crop production", 
                                                 "wild/exotic animal trade/market business", 
                                                 "rancher/farmer animal production business", 
                                                 "meat processing, slaughterhouse, abattoir",
                                                 "hunter/trapper/fisher", 
                                                 "migrant laborer", 
                                                 "nurse, doctor, traditional healer, community health worker", 
                                                 "construction", 
                                                 "extraction of minerals, gas, oil, timber",
                                                 "forager/gatherer/non-timber forest product collector",
                                                 "grocery (vegetables)", "wildlife restaurant business" ,
                                                 "zoo/sanctuary animal health care", 
                                                 "other",
                                                 "missing"),
                               table_lab="Livelihood Activities (past year)\nPrimary")

liv_table <- bind_rows(liv_table_all, liv_table_pri)

# Age (run separate because calculating %tiles)
age_total <- dat %>%
  mutate(age = as.numeric(age)) %>%
  summarise(Mean = mean(age), 
            Minimum = min(age), 
            `First Quartile` = quantile(age, 0.25), 
            Median = median(age), 
            `Third Quartile` = quantile(age, 0.75), 
            Maximum = max(age)) %>%
  t()

age_table <- dat %>%
  mutate(age = as.numeric(age)) %>%
  group_by(concurrent_sampling_site) %>%
  summarise(Mean = mean(age),
            Minimum = min(age),
            `First Quartile` = quantile(age, 0.25),
            Median = median(age),
            `Third Quartile` = quantile(age, 0.75),
            Maximum = max(age)) %>%
  t() %>%
  as.data.frame() %>%
  header_true() %>%
  as_tibble() %>%
  mutate_if(is.factor, function(x) round(as.numeric(as.character(x)), 0)) %>%
  mutate(`Aggregate` = round(age_total, 0)) %>%
  mutate_if(is.numeric, as.character) %>%
  rename_at(site_names$old, function(x) site_names$new[site_names$old == x]) %>%
  rename(` ` = rowname) %>%
  select(` `, site_names$new)

age_table_h <- age_table[1,] %>%
  mutate_all(function(x)"") %>%
  mutate(` ` = "Age")
age_table <- bind_rows(age_table_h, age_table)

# Together
out <- bind_rows(gender_table, age_table, edu_table, time_table, job_table, liv_table)

format_sum_table(out, footer = TRUE) 
```
</details>

<details>
<summary>Household Characteristics</summary>
```{r household-table}
# Dwelling type
dwell_table <- get_sum_table(dat, 
                             pretty_names = site_names, 
                             group_var = "dwelling_permanent_structure",
                             factor_levels = c("yes", 
                                               "no"), 
                             factor_lab  = c("permanent structure", 
                                             "temporary settlement"),  
                             table_lab="Dwelling Type")

# Water source
water_table <- get_sum_table(dat, 
                             pretty_names = site_names, 
                             group_var = "drinking_water_source",
                             factor_levels = c("piped in water/water taps", 
                                               "covered well", 
                                               "uncovered well/pond/river", 
                                               "water truck/rainwater harvest", 
                                               "other", 
                                               "missing"),  
                             table_lab="Source(s) of Water", asterisk = TRUE)

# Water treated
treat_table <- get_sum_table(dat, 
                             pretty_names = site_names, 
                             group_var = "water_treated", 
                             factor_levels = c("yes", 
                                               "no", 
                                               "missing"),  
                             table_lab="Is Water Treated")

# Water treatment method
treat_method_table <-  get_sum_table(dat,
                                     pretty_names = site_names, 
                                     group_var = "water_treatment",
                                     factor_levels = c("boil", 
                                                       "filter",
                                                       "add chlorine or bleach", 
                                                       "solar disinfection", 
                                                       "other",
                                                       "N/A"),  
                                     table_lab="How is Water Treated",
                                     asterisk = TRUE)

# Drinking water used by animals
water_shared_table <- get_sum_table(dat,
                                    pretty_names = site_names,
                                    group_var = "water_used_by_animals",
                                    factor_levels = c("yes",
                                                      "no",
                                                      "missing"),
                                    table_lab = "Drinking Water Source Used by Animals")

# Human waste
waste_table <-  get_sum_table(dat, 
                              pretty_names = site_names, 
                              group_var = "dedicated_location_for_waste",
                              factor_levels = c("yes", 
                                                "no", 
                                                "missing"),  
                              table_lab="Dedicated Location for Human Waste in Dwelling")

# Food
food_table <-  get_sum_table(dat, 
                             pretty_names = site_names, 
                             group_var = "food_storage_containers",
                             factor_levels = c("yes, with covers", 
                                               "yes, without covers", 
                                               "no", 
                                               "missing"),  
                             table_lab="Containers for Food Storage in Household",
                             asterisk = TRUE)

# Occupants
occ_total <- dat %>%
  mutate_at(.vars = vars(rooms_in_dwelling, people_in_dwelling, children_in_dwelling, males_in_dwelling), .funs = as.numeric) %>%
  mutate(people_in_dwelling = people_in_dwelling + 1) %>%
  mutate(males_in_dwelling = ifelse(gender=="male", males_in_dwelling + 1, males_in_dwelling)) %>%
  mutate(rooms_in_dwelling_crowd = ifelse(rooms_in_dwelling == 0, 1, rooms_in_dwelling)) %>%
  mutate(crowding_index = people_in_dwelling/rooms_in_dwelling_crowd) %>%
  summarize(`Number of Children in Household (average)` = mean(children_in_dwelling, na.rm = TRUE),
            `Number of Males in Household (average)` = mean(males_in_dwelling, na.rm = TRUE),
            `Number of People Living in Dwelling (average)` = mean(people_in_dwelling, na.rm = TRUE),
            `Number of Rooms in Dwelling (average)` = mean(rooms_in_dwelling, na.rm = TRUE),
            `Crowding Index (people per room)` = mean(crowding_index, na.rm = TRUE)) %>%
  
  t()

occ_table <- dat %>%
  mutate_at(.vars = vars(rooms_in_dwelling, people_in_dwelling, children_in_dwelling, males_in_dwelling), .funs = as.numeric) %>%
  group_by(concurrent_sampling_site) %>%
  mutate(people_in_dwelling = people_in_dwelling+1) %>%
  mutate(males_in_dwelling = ifelse(gender=="male", males_in_dwelling+1, males_in_dwelling)) %>%
  mutate(rooms_in_dwelling_crowd = ifelse(rooms_in_dwelling == 0, 1, rooms_in_dwelling)) %>%
  mutate(crowding_index = people_in_dwelling/rooms_in_dwelling_crowd) %>%
  summarize(`Number of People Living in Dwelling (average)` = mean(people_in_dwelling, na.rm = TRUE),
            `Number of Rooms in Dwelling (average)` = mean(rooms_in_dwelling, na.rm = TRUE),
            `Crowding Index (people per room)` = mean(crowding_index, na.rm = TRUE),
            `Number of Children in Household (average)` = mean(children_in_dwelling, na.rm = TRUE),
            `Number of Males in Household (average)` = mean(males_in_dwelling, na.rm = TRUE)) %>%
  t() %>%
  as.data.frame() %>%
  header_true() %>%
  as_tibble() %>%
  mutate_if(is.factor, function(x)round(as.numeric(as.character(x)), 1)) %>%
  mutate(`Aggregate` = round(occ_total, 1)) %>%
  mutate_if(is.numeric, as.character) %>%
  rename_at(site_names$old, function(x) site_names$new[site_names$old == x]) %>%
  rename(` ` = rowname) %>%
  select(names(gender_table))

occ_table_h <- occ_table[1,] %>%
  mutate_all(function(x)"") %>%
  mutate(` ` = "Household Occupants")
occ_table <- bind_rows(occ_table_h, occ_table)

# Together 
out <- bind_rows(occ_table, dwell_table, water_table, treat_table, treat_method_table, waste_table, water_shared_table, food_table)
format_sum_table(out, footer = TRUE) 
```
</details>

<details>
<summary>Health Profile</summary>
```{r health-table}
m_treat_table <- get_sum_table(dat, 
                               pretty_names = site_names, 
                               group_var = "treatment", 
                               factor_levels = c("clinic/health center",
                                                 "hospital", 
                                                 "mobile clinic", 
                                                 "community health worker",
                                                 "traditional healer",
                                                 "dispensary or pharmacy"),  
                               table_lab="Location of Treatment for Medical Problems",
                               asterisk = TRUE)

m_treat_table_2 <- get_sum_table(dat, 
                               pretty_names = site_names, 
                               group_var = "treatment_specific", 
                               factor_levels = c("clinic, hospital, or community health worker only", 
                                              "traditional healer only", 
                                              "dispensary or pharmacy only",
                                              "multiple sources"),
                               table_lab="Specific Location of Treatment for Medical Problems")

#had_symptoms_in_year
symp_year_table <- get_sum_table(dat, 
                                 pretty_names = site_names, 
                                 group_var = "had_symptoms_in_last_year",
                                 factor_levels = c("yes",
                                                   "no",
                                                   "missing"),
                                 table_lab = "Had Unusual Illness, Symptoms (past year)")

symp_year_table2 <- get_sum_table(dat, 
                                  pretty_names = site_names, 
                                  group_var = "symptoms_in_last_year",
                                  factor_levels = c("fever with headache and severe fatigue or weakness (encephalitis)",
                                                    "fever with cough and shortness of breath or difficulty breathing (SARI)",
                                                    "fever with muscle aches, cough, or sore throat (ILI)",
                                                    "fever with bleeding or bruising not related to injury (hemorrhagic fever)",
                                                    "fever with diarrhea or vomiting",
                                                    "fever with rash",
                                                    "persistent rash or sores on skin",
                                                    "other",
                                                    "N/A",
                                                    "missing"),
                                  table_lab = "Specific Symptoms",
                                  asterisk = TRUE)

cause_table <- get_sum_table(dat,
                             pretty_names = site_names, 
                             group_var = "sickness_cause", 
                             factor_levels = c("contact with sick people",
                                               "contact with wild animals",
                                               "contact with other animals",
                                               "contact with a corpse/dead body",
                                               "bad food or water",
                                               "bad spirits/witchcraft",
                                               "wound or injury",
                                               "I don't know",
                                               "other",
                                               "N/A"),
                             table_lab = "Perception of Cause of Sickness", 
                             asterisk = TRUE)

sym_other_table <- get_sum_table(dat, 
                                 pretty_names = site_names, 
                                 group_var = "had_symptoms_in_last_year_other_people", 
                                 factor_levels = c("yes", 
                                                   "no",
                                                   "missing"),
                                 table_lab = "Other(s) in Household had Symptoms (past year)", 
                                 asterisk = FALSE)

sym_other_table2 <- get_sum_table(dat,
                                  pretty_names = site_names,
                                  group_var = "symptoms_in_last_year_other_people",
                                  factor_levels  = c("fever with headache and severe fatigue or weakness (encephalitis)",
                                                     "fever with cough and shortness of breath or difficulty breathing (SARI)",
                                                     "fever with muscle aches, cough, or sore throat (ILI)",
                                                     "fever with bleeding or bruising not related to injury (hemorrhagic fever)",
                                                     "fever with diarrhea or vomiting",
                                                     "fever with rash",
                                                     "persistent rash or sores on skin",
                                                     "other",
                                                     "N/A",
                                                     "missing"),
                                  table_lab = "Other Person(s) Specific Symptoms", 
                                  asterisk = TRUE)

died_table <- get_sum_table(dat, 
                            pretty_names = site_names, 
                            group_var = "illness_death",
                            factor_levels = c("yes",
                                              "no", 
                                              "N/A",
                                              "missing"), 
                            table_lab = "Other Person(s) Died from Illness")

# Together 
out <- bind_rows(m_treat_table, m_treat_table_2, symp_year_table, symp_year_table2, cause_table, sym_other_table, sym_other_table2, died_table)

format_sum_table(out, footer = TRUE) 
```
</details>

<details>
<summary>Movement</summary>
```{r movement-table}
movement_table <- get_sum_table(dat, 
                               pretty_names = site_names, 
                               group_var = "travelled", 
                               factor_levels = c("yes",
                                                 "no", 
                                                 "MISSING"),  
                               table_lab="Travelled (past year)")

movement_table_2 <- get_sum_table(dat,
                                  pretty_names = site_names,
                                  group_var = "travel_reason",
                                  factor_levels = c("work",
                                                  "visit family",
                                                  "moved",
                                                  "religious reasons",
                                                  "holiday/vacation",
                                                  "go to hospital/seek medical care",
                                                  "go to market",
                                                  "other",
                                                  "N/A"),
                                  table_lab = "Reasons for Travel",
                                  asterisk = TRUE)
                                              

# Together 
out <- bind_rows(movement_table, movement_table_2)

format_sum_table(out, footer = TRUE) 
```
</details>

<details>
<summary>Animal Contact</summary>
```{r animal-contact-table}
# Scratched/bitten action
act_table <- get_sum_table(dat,
                           pretty_names = site_names, 
                           group_var = "scratched_bitten_action",
                           factor_levels = c("treated",
                                             "untreated",
                                             "N/A"),
                           table_lab = "Action Taken Last Time Scratched, Bitten or Cut While Butchering or Slaughtering")

act_table2 <- get_sum_table(dat,
                            pretty_names = site_names, 
                            group_var = "scratched_bitten_action_specific",
                            factor_levels = c("let someone else take over", 
                                              "wash wound with soap and water", 
                                              "rinse wound with water", 
                                              "bandage wound", 
                                              "visit doctor",  
                                              "nothing - kept working", 
                                              "never butcher or slaughter", 
                                              "n/a"),
                            factor_lab = c("let someone else take over", 
                                           "wash wound with soap and water", 
                                           "rinse wound with water", 
                                           "bandage wound", 
                                           "visit doctor",  
                                           "nothing - kept working", 
                                           "never butcher or slaughter", 
                                           "N/A"),
                            table_lab = "Specific Actions Taken Last Time Scratched, Bitten or Cut While Butchering or Slaughtering",
                            asterisk = TRUE)

# isk_open_wound
risk_table <- get_sum_table(dat, 
                            pretty_names = site_names, 
                            group_var = "risk_open_wound",
                            factor_levels = c("yes", 
                                              "no",
                                              "don't  know",
                                              "other"),  
                            table_lab = "Risks Associated when Slaughtering or Butchering with Open Wound")

# Risk_open_wound2
risk_table2 <- get_sum_table(dat, 
                             pretty_names = site_names, 
                             group_var = "risk_open_wound_specific",
                             factor_levels = c("there are risks, but I don't know what they are", 
                                               "it can make you sick", 
                                               "it can poison you", 
                                               "it can infect you with a disease", 
                                               "N/A"),
                             table_lab = "Specific Risks Associated when Slaughtering or Butchering with Open Wound",
                             asterisk = TRUE)

worried_table <- get_sum_table(dat, pretty_names = site_names, group_var = "worried_about_disease",
                               factor_levels = c("yes",
                                                 "no",
                                                 "missing"),
                               table_lab="Worried about Diseases in Live Animals in Market",
                               asterisk = FALSE)

# Together 
out <- bind_rows(act_table, act_table2, risk_table, risk_table2, worried_table)

format_sum_table(out, footer = TRUE) 

```
</details>


