---
params:
  country: "Indonesia"
title: '<span style="color:red;">DRAFT</span> Mapping Behavioral Risk Data: `r params$country`'
date: "`r Sys.Date()`"
output:
  html_document:
    keep_md: false
    theme: readable
    toc: true
    toc_float: true
    highlight: pygments
    css: ../site-maps/assets/usaid.css
---

```{r setup, include=FALSE}

purrr::walk(list.files(here::here("site-maps/"), full.names = TRUE),
            source, echo = FALSE, verbose = FALSE)

knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, out.extra = '')
country <- params$country

# Read in data
dat <- read_csv(h(paste0("data/raw-behav-", country, ".csv"))) 

# Get Site names
site_names <- read_csv(h(paste0("data/site-name-formatted-", country, ".csv")))

```

```{r load packages, include=FALSE}

library(eidith)
library(tidyverse)
library(lubridate)
library(here)
library(mapview)
library(leaflet)
library(leafpop)
library(janitor)
library(rgeos)
library(rworldmap)
library(bplots) #if(!require(bplots)) devtools::install_github("brooke-watson/bplots")
library(RColorBrewer)
library(maptools)
library(scales)
library(stringr)
library(rlang)
library(shiny)
library(knitr)

```



h <- here::here

USAID_path <- h("/drafts/outputs/assets/USAID-logo.png")
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
