---
params:
  country: ""
  illness_outcomes: ""
  taxa_outcomes: ""
title: '<span style="color:red;">DRAFT</span> Tabular Report: `r params$country`'
date: "`r Sys.Date()`"
output:
  html_document:
    keep_md: false
---
```{r setup, include=FALSE}
purrr::walk(list.files(here::here("R/"), full.names = TRUE),
            source, echo = FALSE, verbose = FALSE)

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

country <- params$country
illness_outcomes <- params$illness
taxa_contact_outcomes <- paste0(params$taxa_outcomes, "_contact")
outcomes <- c(illness_outcomes, taxa_contact_outcomes)

# Read in data
dat <- read_csv(h(paste0("data/tab-behav-", country, ".csv"))) 

# Get Site names
site_names <- read_csv(h(paste0("data/site-name-formatted-", country, ".csv")))

# Get report lookup
table_inputs <- read_csv(h(paste0("tabular-report-tbl-inputs.csv"))) %>%
  mutate(factor_levels = str_split(factor_levels, ";")) 

# Continuous tables
table_inputs_num <- tribble(
  ~group_var,      ~table_lab,    
  "age",            "Age",        
  "crowding_index", "Crowding Index (people per room)"
)
```

```{r make-tbls-cat, include=FALSE}
cat_tables <- map(outcomes, function(endpt){
  
  if(endpt %in% illness_outcomes){outcome_class <- "illness"} 
  if(endpt %in% taxa_contact_outcomes){outcome_class <- "contact"} 
  
  table_inputs_select <- table_inputs %>%
    filter(report %in% c("both", outcome_class))
  
  # Produce categorical tables
  tbs <- map_df(1:nrow(table_inputs_select), function(i){
    #for(i in 1:nrow(table_inputs_select)){
    get_comp_table(dat, 
                   outcome_var = endpt,
                   outcome_class = outcome_class,
                   pretty_names = site_names, 
                   group_var = table_inputs_select$group_var[i], 
                   factor_levels = table_inputs_select$factor_levels[[i]], 
                   table_lab = table_inputs_select$table_lab[i],
                   bars_only = FALSE)
  })
  
  
  i_index <- which(tbs[,2]=="")
  
  h1 <- map_chr(str_split(names(tbs), "\\."), ~.[2]) %>%
    replace_na("")
  h1 <- gsub("Concurrent", "\nConcurrent", h1)
  h2 <- map(str_split(names(tbs), "\\."), ~.[1])
  names(h2) <- names(tbs)
  
  regulartable(tbs) %>%
    set_header_labels(values = h2) %>%
    add_header_row(values = unique(h1), top = TRUE, colwidths = c(1, rep(3, n_distinct(h1)-1))) %>%
    bold(i = i_index, j = 1) %>%
    bold(bold = TRUE, part = "header") %>%
    theme_booktabs() %>%
    align(i = NULL, j = NULL, align = "left", part = "all") %>%
    vline(j = seq(from = 4, to = ncol(tbs)-3, by=3), border = officer::fp_border() ) %>%
    hline(i = i_index[2:length(i_index)]-1, border = officer::fp_border() )
})
names(cat_tables) <- outcomes
```

```{r make-plots-cat, include = FALSE}

cat_plots <- map(outcomes, function(endpt){
  
  if(endpt %in% illness_outcomes){outcome_class <- "illness"} 
  if(endpt %in% taxa_contact_outcomes){outcome_class <- "contact"} 
  
  table_inputs_select <- table_inputs %>%
    filter(report %in% c("both", outcome_class))
  
  # Produce categorical tables
  plots <- map(1:nrow(table_inputs_select), function(i){
    #for(i in 1:nrow(table_inputs_select)){
    pdat <- get_comp_table(dat, 
                           outcome_var = endpt,
                           outcome_class = outcome_class,
                           pretty_names = site_names, 
                           group_var = table_inputs_select$group_var[i], 
                           factor_levels = table_inputs_select$factor_levels[[i]], 
                           table_lab = table_inputs_select$table_lab[i],
                           bars_only = TRUE) 
    
    if(is.null(pdat)){return()}
    pdat %>%
      mutate(concurrent_sampling_site = factor(concurrent_sampling_site, levels = site_names$old)) %>%
      ggplot(., aes(x=concurrent_sampling_site, color = !!sym(table_inputs_select$group_var[i]))) +
      geom_errorbar(aes(ymin = lower, ymax = upper),  position=position_dodge(.9)) +
      geom_point(aes(y = mean), position=position_dodge(.9)) +
      labs(title = "", x="", y=paste("Binomial Probability of", trimws(simple_cap(str_replace_all(endpt, "_", " "))))) +
      theme_classic() +
      theme(axis.text.x = element_text(angle = 60, hjust = 1))
    
  })
})
names(cat_plots) <- outcomes
```

```{r make-tbls-num, include=FALSE}
num_tables <- map(outcomes, function(endpt){
  
  if(endpt %in% illness_outcomes){outcome_class <- "illness"}
  if(endpt %in% taxa_contact_outcomes){outcome_class <- "contact"}
  
  tbs <- map_df(1:nrow(table_inputs_num), function(i){
    # for(i in 1:nrow(table_inputs)){
    get_comp_table_num(dat,
                       outcome_var = endpt,
                       outcome_class = outcome_class,
                       pretty_names = site_names,
                       group_var = table_inputs_num$group_var[i],
                       table_lab = table_inputs_num$table_lab[i],
                       bars_only = FALSE)
  })
  
  
  i_index <- which(tbs[,2]=="")
  
  h1 <- map_chr(str_split(names(tbs), "\\."), ~.[2]) %>%
    replace_na("")
  h1 <- gsub("Concurrent", "\nConcurrent", h1)
  h2 <- map(str_split(names(tbs), "\\."), ~.[1])
  names(h2) <- names(tbs)
  
  regulartable(tbs) %>%
    set_header_labels(values = h2) %>%
    add_header_row(values = unique(h1), top = TRUE, colwidths = c(1, rep(2, n_distinct(h1)-1))) %>%
    bold(i = i_index, j = 1) %>%
    bold(bold = TRUE, part = "header") %>%
    theme_booktabs() %>%
    align(i = NULL, j = NULL, align = "left", part = "all") %>%
    vline(j = seq(from = 3, to = ncol(tbs)-2, by=2), border = officer::fp_border() )  %>%
    hline(i = i_index[2:length(i_index)]-1, border = officer::fp_border() )
})

names(num_tables) <- outcomes
```

```{r make-plots-num, include=FALSE}
num_plots <- map(outcomes, function(endpt){
  
  if(endpt %in% illness_outcomes){outcome_class <- "illness"}
  if(endpt %in% taxa_contact_outcomes){outcome_class <- "contact"}
  
  map(1:nrow(table_inputs_num), function(i){
    # for(i in 1:nrow(table_inputs)){
    get_comp_table_num(dat,
                       outcome_var = endpt,
                       outcome_class = outcome_class,
                       pretty_names = site_names,
                       group_var = table_inputs_num$group_var[i],
                       table_lab = table_inputs_num$table_lab[i],
                       bars_only = TRUE) %>%
      mutate(concurrent_sampling_site = factor(concurrent_sampling_site, levels = site_names$old)) %>%
      ggplot(., aes(x=concurrent_sampling_site, color = response)) +
      geom_errorbar(aes(ymin = lower, ymax = upper),  position=position_dodge(.9)) +
      geom_point(aes(y = mean), position=position_dodge(.9)) +
      labs(title = "", x="", y= simple_cap(table_inputs_num$group_var[i]), color = "") +
      theme_classic() +
      theme(axis.text.x = element_text(angle = 60, hjust = 1))
  })
})
names(num_plots) <- outcomes
```


```{r, include = FALSE}
src <- map_chr(seq_along(outcomes), ~ {
  tab_name <- outcomes[.x]
  knit_expand(text = c("<details>",
                       "<summary>Categorical Tables: {{tab_name}}</summary>",
                       "```{r tab-cat-{{.x}}, echo = FALSE, align = 'left'}", 
                       "cat_tables[[{{.x}}]]",
                       "```",
                       "</details>",
                       "<details>",
                       "<summary>Confidence Interval Plots: {{tab_name}}</summary>",
                       "```{r plot-cat-{{.x}}, echo = FALSE, align = 'left', results='hide'}", 
                       "cat_plots[[{{.x}}]]",
                       "```",
                       "</details>",
                       "<details>",
                       "<summary>Numeric Tables: {{tab_name}}</summary>",
                       "```{r tab-num-{{.x}}, echo = FALSE, align = 'left'}", 
                       "num_tables[[{{.x}}]]",
                       "```",
                       "</details>",
                       "<details>",
                       "<summary>Mean Plots: {{tab_name}}</summary>",
                       "```{r plot-num-{{.x}}, echo = FALSE, align = 'left', results='hide'}", 
                       "num_plots[[{{.x}}]]",
                       "```",
                       "</details>"))
})

```

`r knit_child(text = src)`

