---
params:
  country: ""
  taxa_outcomes: ""
title: '<span style="color:red;">DRAFT</span> Heatmaps: `r params$country`'
date: "`r Sys.Date()`"
output:
  html_document:
    keep_md: false
---

```{r setup, include=FALSE}
purrr::walk(list.files(here::here("R/"), full.names = TRUE),
            source, echo = FALSE, verbose = FALSE)

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, dpi = 300)
country <- params$country
taxa_outcomes <- params$taxa_outcomes

# Read in data
dat <- read_csv(h(paste0("data/raw-behav-", country, ".csv")), col_types = cols()) 
ldat <- read_csv(h(paste0("data/logic-behav-", country, ".csv")), col_types = cols())

# Get site names
site_names <- read_csv(h(paste0("data/site-name-formatted-", country, ".csv")), col_types = cols())

# Get number of rows for sites
nsites <- nrow(site_names) - 1
nrows <- ceiling(nsites/2)
site_height <- 5 + nrows * 5
```

<details>
<summary>Taxa Contact</summary>
```{r heatmap, fig.width = 15, fig.height = 10}
hm <- get_heatmap(ldat, taxa_types = taxa_outcomes, title = "Taxa Contact")
ggsave(plot = hm, file = h("outputs/heatmap-figs", paste0(country, "-heat-map.png")), width = 15, height = 7.5, units = "in")
print(hm)
```
</details>

<details>
<summary>Taxa Contact by Gender</summary>
```{r heatmap-gender, fig.width = 17, fig.height = 10}
gender_dat <- ldat %>%
  left_join(dat %>% select(gender, participant_id), by = "participant_id") %>%
  mutate(gender = na_if(gender, "other")) %>%
  drop_na(gender) %>%
  mutate(gender = factor(gender, levels = c("female", "male"), ordered =TRUE))
hm <- get_heatmap(gender_dat, taxa_types = taxa_outcomes, group_var = "gender", title = "Taxa Contact by Gender")
ggsave(plot = hm, file = h("outputs/heatmap-figs", paste0(country, "-gender-heat-map.png")), width = 15, height = 7.5, units = "in")
print(hm)
```
</details>

<details>
<summary>Taxa Contact by Education</summary>
```{r heatmap-edu, fig.width = 17, fig.height = 17}
edu_dat <- ldat %>%
  left_join(dat %>% select(highest_education, participant_id), by = "participant_id") %>%
  mutate(highest_education = na_if(highest_education, "missing")) %>%
  drop_na(highest_education) %>%
  mutate(highest_education = factor(highest_education, levels = c("none", "primary school", "secondary school", "college/university/professional"), ordered = TRUE))
hm <- get_heatmap(edu_dat, taxa_types = taxa_outcomes, group_var = "highest_education", title = "Taxa Contact by Education")
ggsave(plot = hm, file = h("outputs/heatmap-figs", paste0(country, "-educ-heat-map.png")), width = 15, height = 15, units = "in")
print(hm)
```
</details>

<details>
<summary>Taxa Contact by Age Group</summary>
```{r heatmap-age, fig.width = 17, fig.height = 17}
age_dat <- ldat %>%
  left_join(dat %>% select(age, participant_id), by = "participant_id") %>%
  mutate(age_group = cut(age, 
                         breaks=c(0, 17, 40, 60, Inf), 
                         labels=c("under 18", "18 to 40", "41 to 60", "over 60"))) %>%
  drop_na(age_group)
hm <- get_heatmap(age_dat, taxa_types = taxa_outcomes, group_var = "age_group", title = "Taxa Contact by Age Group")
ggsave(plot = hm, file = h("outputs/heatmap-figs", paste0(country, "-age-heat-map.png")), width = 15, height = 15, units = "in")
print(hm)
```
</details>

<details>
<summary>Taxa Contact by Site</summary>
```{r heatmap-site, fig.width = 17, fig.height = site_height}
site_dat <- ldat %>%
  left_join(dat %>% select(concurrent_sampling_site, participant_id), by = c("participant_id")) %>%
  mutate(concurrent_sampling_site = factor(concurrent_sampling_site, levels = site_names$old, labels = site_names$full_site_name))
hm <- get_heatmap(site_dat, taxa_types = taxa_outcomes, group_var = "concurrent_sampling_site", title = "Taxa Contact by Site")
ggsave(plot = hm, file = h("outputs/heatmap-figs", paste0(country, "-site-heat-map.png")), width = 20, height = 15, units = "in")
print(hm)
```
</details>

