---
params:
  country: "Indonesia"
title: '<span style="color:red;">DRAFT</span> Lasso: `r params$country`'
date: "`r Sys.Date()`"
output:
  html_document:
    keep_md: false
---

```{r setup, include=FALSE}
purrr::walk(list.files(here::here("R/"), full.names = TRUE),
            source, echo = FALSE, verbose = FALSE)

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
country <- params$country 

# Read in data
dat <- read_csv(h(paste0("data/raw-behav-", country, ".csv"))) 

# Save output files
rmarkdown::render(h("scripts/05-lasso.Rmd"),
                  output_file = paste0(country, "-lasso.html"),
                  output_dir = h("lasso"),
                  params = list(country = country))

```

```{r setup and run lasso for illness_outcomes, include=FALSE}

#setup loop to iterate though all illness_outcomes and taxa_outcomes from make.R script

illness_outcomes <- params$illness_outcomes
  
# format data
model_dat <- dat %>%
  filter(country == !!country) %>%
  get_formatted_dat(lifetime = FALSE, combine_illness = FALSE, illness_var = illness_outcomes) %>%
  modify_dwelling_vars() %>%
  discretize_behavioral_variables() %>%
  select(-participant_id)

write_csv(model_dat, h("lasso/models", paste0(country, illness_outcomes, "-model-dat.csv")))

# create matrix
cleaned_dat <- model_dat %>%
  make_matrix(restricted_interactions = TRUE, illness_outcomes = illness_outcomes) %>%
  remove_colinear_columns()

# fit lasso
lasso_fit <- fit_lasso_model(cleaned_dat$model_data_matrix, response = pull(model_dat, !!illness_outcomes))

write_rds(lasso_fit, h("lasso/models", paste0(country, illness_outcomes, -"lasso-fit.rds")))

# get odds ratios for reporting
coefs <- coef(lasso_fit) %>%
  as.matrix() %>%
  as.data.frame() %>%
  rownames_to_column("variable") %>%
  rename(effect=s0) %>%
  mutate(effect = exp(effect)) %>%
  arrange(-effect)

write_csv(coefs, h("lasso/models", paste0(country, illness_outcomes, "-odds-ratio-lasso.csv")))

```


```{r setup and run lasso for taxa_outcomes, include=FALSE}

#setup loop to iterate though all illness_outcomes and taxa_outcomes from make.R script

taxa_outcomes <- params$taxa_outcomes
  
# format data
model_dat <- dat %>%
  filter(country == !!country) %>%
  get_formatted_dat(lifetime = FALSE, combine_illness = FALSE, illness_var = c("ili", "sari", "encephalitis",
                                                                               "hemorrhagic")) %>%
  modify_dwelling_vars() %>%
  discretize_behavioral_variables() %>%
  select(-starts_with(taxa_outcomes)) %>%
  mutate(taxa_outcomes = !"no_"(taxa_outcomes)) %>%
  select(-participant_id,
         starts_with("no_"))

sapply(model_dat, table)

write_csv(model_dat, h("lasso/models", paste0(country, taxa_outcomes, "-model-dat.csv")))

# create matrix
cleaned_dat <- model_dat %>%
  make_matrix(restricted_interactions = TRUE, taxa_outcomes = taxa_outcomes) %>%
  remove_colinear_columns()

# fit lasso
lasso_fit <- fit_lasso_model(cleaned_dat$model_data_matrix, response = pull(model_dat, !!taxa_outcomes))

write_rds(lasso_fit, h("lasso/models", paste0(country, taxa_outcomes, -"lasso-fit.rds")))

# get odds ratios for reporting
coefs <- coef(lasso_fit) %>%
  as.matrix() %>%
  as.data.frame() %>%
  rownames_to_column("variable") %>%
  rename(effect=s0) %>%
  mutate(effect = exp(effect)) %>%
  arrange(-effect)

write_csv(coefs, h("lasso/models", paste0(country, taxa_outcomes, "-odds-ratio-lasso.csv")))

```


<details>
<summary>Lasso Regression - Illness</summary>
```{r read lasso model and save png output for illness_outcomes, fig.width = 10, fig.height = 7}

#lasso_fit <- read_rds(h("lasso/models", paste0(country, illness_outcomes, "-lasso-fit.rds")))
#model_dat <- read_csv(h("lasso/models", paste0(country, illness_outcomes, "-model-dat.csv")))

if(!is.infinite(lasso_fit$lambda)){
  p <- plot_lasso_fit(lasso_fit, model_dat, pretty_names = TRUE, vert_line = FALSE) +
    scale_fill_manual(values = c("#7E03A8FF", "#F89441FF"))
  
    ggsave(plot = p, file = h("lasso/outputs", paste0(country, illness_outcomes, "-lasso-plot.png")), width = 10, height = 7, units = "in")
}else{
  p <- "Lasso did not converge"
}
print(p)

```
</details>

<details>
<summary>Lasso Regression - Taxa</summary>
```{r read lasso model and save png output for taxa_outcomes, fig.width = 10, fig.height = 7}

#lasso_fit <- read_rds(h("lasso/models", paste0(country, taxa_outcomes, "-lasso-fit.rds")))
#model_dat <- read_csv(h("lasso/models", paste0(country, taxa_outcomes, "-model-dat.csv")))

if(!is.infinite(lasso_fit$lambda)){
  p <- plot_lasso_fit(lasso_fit, model_dat, pretty_names = TRUE, vert_line = FALSE) +
    scale_fill_manual(values = c("#7E03A8FF", "#F89441FF"))
  
    ggsave(plot = p, file = h("lasso/outputs", paste0(country, taxa_outcomes, "-lasso-plot.png")), width = 10, height = 7, units = "in")
}else{
  p <- "Lasso did not converge"
}
print(p)

```
</details>