---
params:
  country: ""
  taxa_outcomes: ""
title: '<span style="color:red;">DRAFT</span> Heatmaps: `r params$country`'
date: "`r Sys.Date()`"
output:
  html_document:
    keep_md: false
---

```{r setup, include=FALSE}
purrr::walk(list.files(here::here("R/"), full.names = TRUE),
            source, echo = FALSE, verbose = FALSE)

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, dpi = 300)
country <- "Thailand"
taxa_types <- taxa_names

# Read in data
dat <- read_csv(h(paste0("data/raw-behav-", country, ".csv")), col_types = raw_specs) 
ldat <- read_csv(h(paste0("data/logic-behav-", country, ".csv")), col_types = cols())
```
<small>_Click on the_ ▶ _︎arrows to expand sections._</small>

<details>
<summary>Taxa Contact</summary>
```{r heatmap, fig.width = 15, fig.height = 10}
contx_types = c('pets',
                'handled',
                'raised',
                'feces in or near food',
                'in house',
                'cooked/handled',
                'eaten raw/undercooked',
                'eaten sick',
                'found dead/collected',
                'scratched/bitten',
                'hunted/trapped',
                'slaughtered')

fct_levels <- c('pets',
                'handled',
                'raised',
                'feces in or near food',
                'in house',
                'cooked handled',
                'eaten raw undercooked',
                'eaten sick',
                'found dead collected',
                'scratched bitten',
                'hunted trapped',
                'slaughtered')

taxa_types_col <- paste(taxa_types, collapse = "|")
group_var <- ""

cdat <- ldat %>%
  group_by_at(vars(suppressWarnings(one_of(!!group_var)))) %>%
  count() %>%
  rename(tot = n)

hdat <- ldat %>%
  select(suppressWarnings(one_of(group_var)), matches(taxa_types_col)) %>%
  gather(key = key, value = value, -suppressWarnings(one_of(group_var))) %>%
  filter(value == TRUE) %>%
  group_by_at(vars(suppressWarnings(one_of(group_var)), key)) %>%
  count() %>%
  ungroup() %>%
  mutate(taxa = str_extract(key, taxa_types_col),
         taxa = str_replace(taxa, "_", "/"),
         contx = str_replace_all(key, paste0("_|contact|", taxa_types_col), " ") %>%
           trimws(.) %>%
           ifelse(. == "none", "no contact", .) %>%
           factor(., levels = fct_levels,
                  labels = contx_types)) %>%
  select(-key) %>% 
  filter(contx !=  "no contact")

hdat <- hdat %>%
  complete(contx, nesting(taxa), fill = list(n = 0)) %>%
  mutate(tot = cdat$tot) %>%
  mutate(perc = round(100* n/tot)) %>%
  mutate(lab = paste0( n))

p <- ggplot(data = hdat, aes(x = taxa, y = contx, fill = perc, label = lab)) +
  geom_tile(color = 'gray') +
  geom_label(fontface='bold', fill="white", size = 3) +
  scale_x_discrete(position = 'bottom') +
  scale_fill_viridis_c(guide = FALSE) +
  theme_fivethirtyeight() +
  theme(plot.title = element_text(hjust=0.5),
        strip.text = element_text(size=14),
        axis.text.y = element_text(size=12, color="black"),
        axis.text.x = element_text(size=12, color="black", angle = 60, vjust = 1, hjust = 0.95)) +
  labs(title = "", x="", y="")

ggsave(plot = p, file = h("outputs/heatmap-figs", paste0(country, "-heat-map.png")), width = 15, height = 7.5, units = "in")
print(p)
```
</details>
