---
params:
  country: "Indonesia"
title: '<span style="color:red;">DRAFT</span> Behavioral Report: `r params$country`'
date: "`r Sys.Date()`"
output:
  html_document:
    keep_md: false
---
```{r setup, include=FALSE}
source(here::here("R/functions.R"))
source(here::here("R/packages.R"))

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
country <- params$country

# Read in data
dat <- read_csv(h(paste0("data/raw-behav-", country, ".csv"))) %>%
  mutate_if(is.character, ~replace_na(., "N/A"))

# Get Site names
site_names <- read_csv(h(paste0("data/site-name-formatted-", country, ".csv")))
```

<small>_Click on the_ ▶ _︎arrows to expand sections._</small>


<details>
<summary>Site Characteristics</summary>
```{r site-general-table}
# Seasons
season_sites <- get_sum_table(dat, 
                              pretty_names = site_names, 
                              group_var = "season", 
                              factor_levels = c("Dry",
                                                "Wet"),
                              factor_lab = c("dry",
                                             "wet"),
                              table_lab="Sampling Season")


# human_density_impact
sites_human_density_impact <- get_sum_table(dat, 
                                            pretty_names = site_names, 
                                            group_var = "human_density_impact", 
                                            factor_levels = c("urban",
                                                              "peri-urban",
                                                              "rural",       
                                                              "low disturbance"), 
                                            table_lab="Human Density at Sampling Sites")


# disease_transmission_interfaces
sites_disease_transmission_interfaces <- get_sum_table(dat, 
                                                       pretty_names = site_names, 
                                                       group_var = "disease_transmission_interfaces", 
                                                       factor_levels = c("animal production",
                                                                         "crop production", 
                                                                         "dwellings and temporary settlements",
                                                                         "extractive industry",
                                                                         "market and value chain", 
                                                                         "natural areas", 
                                                                         "wildlife restaurant", 
                                                                         "human hospital",
                                                                         "zoos and sanctuaries",
                                                                         "outbreak investigation"), 
                                                       table_lab="Disease Transmission Interface at Sampling Sites",
                                                       asterisk = TRUE)


# veterinarian_care
sites_veterinarian_care <- get_sum_table(dat, 
                                         pretty_names = site_names, 
                                         group_var = "veterinarian_care", 
                                         factor_levels = c("yes",
                                                           "no",
                                                           "N/A"), 
                                         table_lab="Veterinarian Care at Sampling Sites")


# sampling_area_size
sites_sampling_area_size <- get_sum_table(dat, 
                                          pretty_names = site_names, 
                                          group_var = "sampling_area_size", 
                                          factor_levels = c("small <650 square meters",
                                                            "medium 650-3500 square meters",
                                                            "large 3500-7000 square meters",       
                                                            "extra large >7000 square meters",
                                                            "N/A"),
                                          table_lab="Size of Sampling Sites")

# Together - export to word and print to html
out <- bind_rows(season_sites, sites_human_density_impact, sites_disease_transmission_interfaces, sites_veterinarian_care, sites_sampling_area_size)

format_sum_table(out) 
  
```
</details>

